version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis-db-dev
    ports:
      - "6379:6379"
  mongodb:
    image: mongo:latest
    container_name: mongo-db-dev
    ports:
      - "27017:27017"
  cassandra:
    image: cassandra:latest
    container_name: cassandra-db-dev
