version: '3'
services:
  redis:
    image: redis
    container_name: redis-db
    expose:
      - "6379"
  mongodb:
    image: mongo
    expose:
      - "27017"
    container_name: mongo-db
  cassandra:
    image: cassandra:latest
    container_name: cassandra-db
    expose:
      - "9042"
  api:
    build:
      dockerfile:
        api/Dockerfile
      context: ..
    ports:
      - "8000:80"